# Generated by Django 5.1.2 on 2024-10-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivriety',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
