# Generated by Django 5.1.2 on 2024-10-30 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_chaivriety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivriety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MaxValueValidator(500000.0)]),
        ),
    ]
