# Generated by Django 5.1.2 on 2024-10-31 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_chaicertificate_reviews_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='locatistore_on',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='date_add',
        ),
        migrations.AddField(
            model_name='reviews',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
